# Generated by Django 3.2.6 on 2022-07-09 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntari',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200, null=True, verbose_name='Nume')),
                ('last_name', models.CharField(max_length=200, null=True, verbose_name='Prenume')),
                ('data', models.DateField(null=True, verbose_name='Data Nasterii')),
                ('mail', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=200, null=True, verbose_name='Nr. Telefon')),
                ('gender', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=200, null=True, verbose_name='Sex')),
                ('adress', models.CharField(max_length=200, null=True, verbose_name='Adresă')),
                ('nr', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True, verbose_name='Oras')),
                ('judet', models.CharField(max_length=200, null=True, verbose_name='Judet')),
                ('country', models.CharField(max_length=200, null=True, verbose_name='Tara')),
                ('Facultate', models.CharField(max_length=200, null=True)),
                ('specializare', models.CharField(max_length=200, null=True, verbose_name='Specializare')),
                ('an', models.CharField(choices=[('Anul I', 'Anul I'), ('Anul II', 'Anul II'), ('Anul III', 'Anul III'), ('Anul IV', 'Anul IV'), ('Anul V', 'Anul V'), ('Anul VI', 'Anul VI')], max_length=200, null=True, verbose_name='Anul de studiu')),
                ('picture', models.ImageField(upload_to = None)),
                ('social', models.URLField(null=True, verbose_name='Adresa Facebook')),
                ('nume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Eveniment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Activitate')),
                ('locate', models.CharField(max_length=200, null=True, verbose_name='Locatie')),
                ('data', models.DateTimeField(null=True, verbose_name='Data si ora')),
                ('timp', models.FloatField(null=True, verbose_name='Durata')),
                ('descriere', models.TextField(blank=True, null=True, verbose_name='Descriere')),
                ('coord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.voluntari')),
            ],
        ),
    ]
